import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Nav } from "@/components/layout/nav";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Portfolio - insta",
  // description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const messages = await getMessages();

  return (
    <html lang="en">
      <body className={inter.className}>
      <NextIntlClientProvider messages={messages}>
        <Nav/>
        {children}
      </NextIntlClientProvider>
      </body>
    </html>
  );
}
