import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Montserrat } from 'next/font/google';
import "./globals.css";
import { Nav } from "@/components/layout/nav";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Footer } from "@/components/layout/footer";

const inter = Inter({ subsets: ["latin"] });
const monsterRat = Montserrat ({subsets: ['latin'], display: 'swap',})


export const metadata: Metadata = {
  title: "Portfolio - insta",
  // description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const messages = await getMessages();

  return (
    <html lang="en" >
      <body className={monsterRat.className}>
      <NextIntlClientProvider messages={messages}>
        <Nav/>
        {children}
      </NextIntlClientProvider>
      <Footer />
      </body>
    </html>
  );
}
